import React from "react";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export const Layout: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {children}
        <div className={styles.grid}>
          <Link passHref href="/">
            <a className={styles.card}>
              <h2>Home</h2>
              <p>{`Basic Page without anything`}</p>
            </a>
          </Link>
          {/* eslint-disable @next/next/no-html-link-for-pages */}
          <a href="/route1" className={styles.card}>
            <h2>Route 1</h2>
            <p>{`Server Side Rendering Example`}</p>
          </a>
          <Link passHref href="/nested/route2">
            <a className={styles.card}>
              <h2>Route 2</h2>
              <p>{`Static Side Generation Example`}</p>
            </a>
          </Link>
          <Link passHref href="/route3">
            <a className={styles.card}>
              <h2>Route 3</h2>
              <p>{`Client Side Rendering Example`}</p>
            </a>
          </Link>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
